import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    alignItems: 'center',
    backgroundColor: '#F4F4F4',
  },
  header: {
    backgroundColor: '#00A896',
    alignItems: 'center',
    width: '100%',
    height: '7%',
  },
  titleHeader: {
    marginTop: '3%',
    textAlign: 'center',
    fontSize: 20,
    fontFamily: 'boldIBM',
    color: '#fff',
  },
  iconExit: {
    marginTop: '2%',
    left: '-45%',
    width: 30,
    height: 30,
    resizeMode: 'contain',
    position: 'absolute',
  },
  frame: {
    alignItems: 'center',
    borderWidth: 1,
    borderTopWidth: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderRadius: 10,
    borderColor: '#CCC',
    width: '95%',
    height: '90%',
  },
  frame2: {
    marginTop: '3%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#00A896',
    width: '97%',
    height: '97%',
  },
  containerbalence: {
    width: '60%',
    height: '10%',
    margin: 10,
  },
  pixValue: {
    padding: 5,
    color: '#1E1E1E',
    textAlign: 'center',
    fontFamily: 'ibmRegular',
    fontSize: 36,
    borderBottomWidth: 1,
    borderColor: '#00A896',
  },
  containerData: {
    flexDirection: 'row',
    top: 20,
    width: '72%',
    height: '15%',
  },
  Title: {
    width: 80,
    height: 75,
    left: '-35%',
  },
  atributte: {
    width: 150,
    height: 76,
    left: '70%',
  },
  TitlepixDate: {
    fontFamily: 'ibmRegular',
    fontSize: 18,
    textAlign: 'left',
    width: '50%',
  },
  pixDate: {
    fontFamily: 'ibmRegular',
    fontSize: 18,
    textAlign: 'right',
  },
  TitleTimeSent: {
    fontFamily: 'ibmRegular',
    fontSize: 18,
    textAlign: 'left',
  },
  TimeSent: {
    fontFamily: 'ibmRegular',
    fontSize: 18,
    textAlign: 'right',
  },
  TitleIDtransation: {
    fontFamily: 'ibmRegular',
    fontSize: 18,
    textAlign: 'left',
  },
  IDtransation: {
    fontFamily: 'ibmRegular',
    fontSize: 18,
    textAlign: 'right',
    justifyContent: 'space-between',
  },
  containerSent: {
    left: '-20%',
    marginTop: '15%',
  },
  titleSent: {
    textAlign: 'left',
    fontFamily: 'boldIBM',
    fontSize: 20,
    color: '#00A896',
    marginBottom: 15,
  },
  nameSent: {
    textAlign: 'left',
    fontFamily: 'ibmRegular',
    fontSize: 20,
    marginBottom: 1,
  },
  cpfSent: {
    textAlign: 'left',
    fontFamily: 'ibmRegular',
    fontSize: 20,
    marginBottom: 1,
  },
  bankSent: {
    textAlign: 'left',
    fontFamily: 'ibmRegular',
    fontSize: 20,
    marginBottom: 1,
  },
  containerDestination: {
    left: '-20%',
    marginTop: '1%',
  },
  titleDestination: {
    textAlign: 'left',
    fontFamily: 'boldIBM',
    fontSize: 20,
    marginTop: 20,
    color: '#00A896',
    marginBottom: 15,
  },
  nameDestination: {
    textAlign: 'left',
    fontFamily: 'ibmRegular',
    fontSize: 20,
    marginBottom: 1,
  },
  cpfDestination: {
    textAlign: 'left',
    fontFamily: 'ibmRegular',
    fontSize: 20,
    marginBottom: 1,
  },
  bankDestination: {
    textAlign: 'left',
    fontFamily: 'ibmRegular',
    fontSize: 20,
    marginBottom: 1,
  },
  receiptText: {
    color: '#FFF',
    fontFamily: 'boldIBM',
    fontSize: 18,
    textAlign: 'center',
    margin: 15,
  },
  receiptBtn: {
    borderRadius: 10,
    alignSelf: 'center',
    backgroundColor: '#00A896',
    alignItems: 'center',
    position: 'absolute',
    width: '75%',
    height: '9%',
    bottom: '5%',
  },
});
export default styles;
